[package]
name = "final_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
k256 = "0.11"
sha2 = "0.9"
base64 = "0.13"
